[General]
ConfigVersion=1
ManagedProfile=word-compatible

[Goal]
History=true
Minutes=30
StreakMinimum=100
Streaks=true
Type=1
Words=1000

[Preferences]
AlwaysCenter=false
BlockCursor=false
ConfirmDiscard=true
Profile=normal
SmartDoubleQuotes=-1
SmartQuotes=true
SmartSingleQuotes=-1
SmoothFonts=true
StartFullscreen=false
TypewriterSounds=false

[Save]
DefaultFormat=docx
RememberPositions=true
WriteBOM=false

[SceneList]
Divider=##
Width=300

[Spelling]
HighlightMisspelled=true
IgnoreNumbers=true
IgnoreUppercase=true
Language=en_US

[Stats]
CharactersPerPage=1500
PageSizeType=2
ParagraphsPerPage=5
ShowCharacters=true
ShowPages=true
ShowParagraphs=true
ShowWords=true
WordcountType=0
WordsPerPage=250

[SymbolsDialog]
Current=32
Group=1
Size=@Size(750 500)

[ThemeManager]
Size=@Size(900 600)
Theme=managed-word
ThemeDefault=false

[Toolbar]
Actions=New, Open, Save, |, Undo, Redo, |, Cut, Copy, Paste, |, Find, Replace, |, Themes
Shown=true
Style=2

[View]
AlwaysShowFooter=true
AlwaysShowHeader=true
AlwaysShowScrollbar=true

[Window]
FocusedText=0
Fullscreen=false
MenuIcons=true
RestoreSession=true
