apiVersion: cybops.nftables/v1
kind: NftablesServiceOverlay
metadata:
  name: matrix-synapse
  description: Matrix Synapse overlay.
  merge_priority: 50
services:
  matrix_client_federation:
    enabled: true
    direction: inbound
    protocols:
    - tcp
    ports:
    - 443
    - 8448
    allow:
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      interfaces:
      - eth0
      - en*
      - __INSTALLER_MANAGED_NETWORK_ETHERNET_IFACE__
      - wlan0
      - wl*
      - __INSTALLER_MANAGED_NETWORK_WIFI_IFACE__
    sensitive: false
