apiVersion: cybops.nftables/v1
kind: NftablesServiceOverlay
metadata:
  name: ntp-server
  description: Inbound NTP server overlay. LAN/VPN only by default.
  merge_priority: 50
services:
  ntp_server:
    enabled: true
    direction: inbound
    protocols:
    - udp
    ports:
    - 123
    allow:
      ipv4:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 10.8.0.0/24
      ipv6:
      - fc00::/7
      - fe80::/10
      - fd00:8::/64
      interfaces:
      - eth0
      - en*
      - __INSTALLER_MANAGED_NETWORK_ETHERNET_IFACE__
      - wlan0
      - wl*
      - __INSTALLER_MANAGED_NETWORK_WIFI_IFACE__
      - wg0
