apiVersion: cybops.nftables/v1
kind: NftablesServiceOverlay
metadata:
  name: prometheus
  description: Prometheus and node exporter monitoring overlay.
  merge_priority: 50
services:
  prometheus_server:
    enabled: false
    direction: inbound
    protocols:
    - tcp
    ports:
    - 9090
    allow:
      ipv4:
      - 10.0.0.0/8
      - 192.168.0.0/16
      - 10.8.0.0/24
      ipv6:
      - fc00::/7
      - fd00:8::/64
      interfaces:
      - eth0
      - en*
      - __INSTALLER_MANAGED_NETWORK_ETHERNET_IFACE__
      - wlan0
      - wl*
      - __INSTALLER_MANAGED_NETWORK_WIFI_IFACE__
      - wg0
    sensitive: true
    log: false
  node_exporter:
    enabled: true
    direction: inbound
    protocols:
    - tcp
    ports:
    - 9100
    allow:
      ipv4:
      - 10.0.0.0/8
      - 192.168.0.0/16
      - 10.8.0.0/24
      ipv6:
      - fc00::/7
      - fd00:8::/64
      interfaces:
      - eth0
      - en*
      - __INSTALLER_MANAGED_NETWORK_ETHERNET_IFACE__
      - wlan0
      - wl*
      - __INSTALLER_MANAGED_NETWORK_WIFI_IFACE__
      - wg0
    sensitive: true
    log: false
  alertmanager:
    enabled: false
    direction: inbound
    protocols:
    - tcp
    ports:
    - 9093
    allow:
      ipv4:
      - 10.0.0.0/8
      - 192.168.0.0/16
      - 10.8.0.0/24
      ipv6:
      - fc00::/7
      - fd00:8::/64
      interfaces:
      - eth0
      - en*
      - __INSTALLER_MANAGED_NETWORK_ETHERNET_IFACE__
      - wlan0
      - wl*
      - __INSTALLER_MANAGED_NETWORK_WIFI_IFACE__
      - wg0
    sensitive: true
    log: false
