apiVersion: cybops.nftables/v1
kind: NftablesServiceOverlay
metadata:
  name: smtp-server
  description: Inbound SMTP server overlay.
  merge_priority: 50
services:
  smtp_server:
    enabled: true
    direction: inbound
    protocols:
    - tcp
    ports:
    - 25
    - 465
    - 587
    allow:
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      interfaces:
      - eth0
      - en*
      - __INSTALLER_MANAGED_NETWORK_ETHERNET_IFACE__
      - wlan0
      - wl*
      - __INSTALLER_MANAGED_NETWORK_WIFI_IFACE__
    sensitive: false
    rate_limit: 100/second burst 200 packets
